### ISSUE TITLE
Feedback for guide-microprofile-rest-client

### ISSUE THREAD

**Issue by AustinSeto** [OpenLiberty/cloud-hosted-guide-converter#55]
Tested using login with Github, failed with:

```
An error occurred when signing you in to Open Liberty Hands On.
We are sorry, you are not authorized to access Open Liberty Hands On via this channel. Please contact your learning administrator or manager in order to access Open Liberty Hands On.

Error Details:
Authentication process cancelled
```

Retried log in with LinkedIn. This succeeds. Both my LinkedIn and Github are registered under the same e-mail address though. 

Tested on Windows 10 on Firefox

***

# Step 1

- [ ] CDI link appears to be duplicated, appearing twice, with the second instance overwriting what should be a link to a blog post for the `RestClientBuilder`.

# Step 2

- [x] In message `The defaultServer server is ready to run a smarter planet.`, the word "is" is bolded for some reason.
- [x] When it asks you to point the browser to a URL, this isn't applicable for the cloud hosted guides 
  - Previously mentioned in https://github.com/OpenLiberty/cloud-hosted-guide-converter/issues/53
  - Perhaps mentions of localhost:9080 can be replaced with something like `austinseto-9080.theiadocker-24.proxy.cognitiveclas.ai` (the URL I had) or similar?
  - `curl` command cannot be used before opening another terminal as the application is running the first terminal
- [x] Descriptions of URLs have parts of the URL italicized for some reason
- [x] Unsure if statement about FQDN is applicable on the cloud hosted guides

# Step 3

- [x] In example message `Press the Enter key to run tests on demand` the word "press" is bolded and "on" is highlighted

# Step 6

- [x] It says to "select either approach" but no approaches are shown

# Step 7

- [x] In description of `testDefaultLocalHost()` the URL has a backslash at the start

# Step 8

- [ ] Hyperlink for `Hostname with verification...` is duplicated, overwriting the hyperlink `MicroProfile Rest Client specification` that appears on openliberty.io

**Comment by jakub-pomykala** [comment]
The feedback for step 7, could you please open an issue about this in the repo for guide-microprofile-rest-client as the backslash is in the original guide aswell.

**Comment by jakub-pomykala** [comment]
Done it now :)

**Comment by jakub-pomykala** [comment]
@AustinSeto do you think we should remove every single mention of FQDN or is that going too far? Do we still need to keep some of the references and just remove others. If it is okay to remove every single one of the references then this is something we can look at doing in the near future. Let me know :)

**Comment by AustinSeto** [comment]
@jakub-pomykala I'm not sure if any other guides mention the FQDN. I just tried it on the quick lab and the guide content that suggests using the `hostname` command doesn't return the proper hostname. 

<img width="398" alt="Screen Shot 2021-01-15 at 11 16 57 AM" src="https://user-images.githubusercontent.com/24989956/104751319-3b94a000-5723-11eb-8262-4ca09f40a279.png">

I saw issue #66 already opened up for a similar issue with the hostname. I think for the FQDN issue here, I don't think it's on other guides so for now I'll just see if a minor adjustment could be made to the microprofile rest client guide to make it applicable for both the quick lab and a user's machine.

**Comment by AustinSeto** [comment]
Re-reviewed, what is returned by the `hostname` command on the cloud hosted version does actually work, and after looking into content, I think the paragraph is still applicable and doesn't need changes. 

Links not converting correctly still appears to occur. Same links as previously mentioned - the blog post link for `RestClientBuilder` in step 1, and the MP Rest Client specification link in step 8.

**Comment by AustinSeto** [comment]
After last rebuild, all links appearing correctly now
